<?php
defined( 'ABSPATH' ) || exit;

/** Admin screens and protected actions. */
class QRip_Admin {
	public static function init() {
		add_action( 'admin_menu', array( __CLASS__, 'menu' ) );
		add_action( 'admin_post_qrip_save', array( __CLASS__, 'save' ) );
		add_action( 'admin_post_qrip_status', array( __CLASS__, 'status' ) );
		add_action( 'admin_post_qrip_delete', array( __CLASS__, 'delete' ) );
		add_action( 'admin_post_qrip_download', array( __CLASS__, 'download' ) );
	}
	public static function menu() { add_menu_page( __( 'QR Codes', 'qrip' ), __( 'QR Codes', 'qrip' ), 'manage_options', 'qrip', array( __CLASS__, 'page' ), 'dashicons-grid-view', 58 ); }
	private static function authorize( $action ) { if ( ! current_user_can( 'manage_options' ) ) { wp_die( esc_html__( 'You are not allowed to manage QR codes.', 'qrip' ), 403 ); } check_admin_referer( $action ); }
	private static function admin_url( $args = array() ) { return add_query_arg( $args, admin_url( 'admin.php?page=qrip' ) ); }

	public static function save() {
		self::authorize( 'qrip_save' ); $id = absint( $_POST['id'] ?? 0 ); $result = QRip_Core::save_record( wp_unslash( $_POST ), $id );
		if ( is_wp_error( $result ) ) { wp_safe_redirect( self::admin_url( array( 'action' => 'edit', 'id' => $id, 'error' => rawurlencode( $result->get_error_message() ) ) ) ); exit; }
		wp_safe_redirect( self::admin_url( array( 'action' => 'edit', 'id' => $result, 'updated' => 1 ) ) ); exit;
	}
	public static function status() { self::authorize( 'qrip_status' ); $id = absint( $_POST['id'] ?? 0 ); $record = QRip_Core::record( $id ); if ( ! $record ) { wp_die( esc_html__( 'QR code not found.', 'qrip' ), 404 ); } update_post_meta( $id, QRip_Core::META_STATUS, 'paused' === $record['status'] ? 'active' : 'paused' ); update_post_meta( $id, QRip_Core::META_UPDATED_BY, get_current_user_id() ); wp_safe_redirect( self::admin_url( array( 'updated' => 1 ) ) ); exit; }
	public static function delete() { self::authorize( 'qrip_delete' ); $id = absint( $_POST['id'] ?? 0 ); if ( QRip_Core::record( $id ) ) { wp_delete_post( $id, true ); } wp_safe_redirect( self::admin_url( array( 'deleted' => 1 ) ) ); exit; }
	public static function download() {
		self::authorize( 'qrip_download' ); $id = absint( $_GET['id'] ?? 0 ); $format = sanitize_key( $_GET['format'] ?? '' ); $record = QRip_Core::record( $id );
		if ( ! $record || ! in_array( $format, array( 'svg', 'png' ), true ) ) { wp_die( esc_html__( 'QR code download not found.', 'qrip' ), 404 ); }
		$result = QRip_Core::qr_result( $record['slug'], $format ); nocache_headers(); header( 'Content-Type: ' . $result->getMimeType() ); header( 'Content-Disposition: attachment; filename="' . QRip_Core::download_filename( $record, $format ) . '"' ); header( 'X-Content-Type-Options: nosniff' ); echo $result->getString(); exit;
	}
	private static function action_url( $action, $args, $nonce_action ) { return wp_nonce_url( add_query_arg( array_merge( array( 'action' => $action ), $args ), admin_url( 'admin-post.php' ) ), $nonce_action ); }
	private static function download_url( $id, $format ) { return self::action_url( 'qrip_download', array( 'id' => $id, 'format' => $format ), 'qrip_download' ); }

	public static function page() {
		if ( ! current_user_can( 'manage_options' ) ) { return; }
		$action = sanitize_key( $_GET['action'] ?? '' ); if ( 'new' === $action || 'edit' === $action ) { self::form( absint( $_GET['id'] ?? 0 ) ); return; } self::listing();
	}
	private static function listing() {
		$search = sanitize_text_field( wp_unslash( $_GET['s'] ?? '' ) );
		$query = new WP_Query( array( 'post_type' => QRip_Core::POST_TYPE, 'post_status' => 'any', 'posts_per_page' => 50, 's' => $search, 'orderby' => 'modified', 'order' => 'DESC' ) );
		if ( $search ) { $query = new WP_Query( array( 'post_type' => QRip_Core::POST_TYPE, 'post_status' => 'any', 'posts_per_page' => 50, 'orderby' => 'modified', 'order' => 'DESC', 'meta_query' => array( 'relation' => 'OR', array( 'key' => QRip_Core::META_SLUG, 'value' => $search, 'compare' => 'LIKE' ), array( 'key' => QRip_Core::META_DESTINATION, 'value' => $search, 'compare' => 'LIKE' ) ) ) ); }
		?> <div class="wrap qrip-admin"><h1 class="wp-heading-inline"><?php esc_html_e( 'QRip QR Codes', 'qrip' ); ?></h1> <a class="page-title-action" href="<?php echo esc_url( self::admin_url( array( 'action' => 'new' ) ) ); ?>"><?php esc_html_e( 'Add New', 'qrip' ); ?></a><hr class="wp-header-end">
		<form method="get"><input type="hidden" name="page" value="qrip"><p class="search-box"><label class="screen-reader-text" for="qrip-search">Search QR codes</label><input id="qrip-search" name="s" value="<?php echo esc_attr( $search ); ?>"><button class="button"><?php esc_html_e( 'Search', 'qrip' ); ?></button></p></form>
		<table class="wp-list-table widefat fixed striped"><thead><tr><th>Name</th><th>Managed URL</th><th>Destination</th><th>Status</th><th>Scans</th><th>Last scan</th><th>Updated</th><th>Actions</th></tr></thead><tbody><?php foreach ( $query->posts as $post ) { $r = QRip_Core::record( $post->ID ); self::row( $r ); } if ( ! $query->posts ) { echo '<tr><td colspan="8">' . esc_html__( 'No QR codes found.', 'qrip' ) . '</td></tr>'; } ?></tbody></table>
		<h2><?php esc_html_e( 'Print guidance', 'qrip' ); ?></h2><p><?php esc_html_e( 'Create one code per distinct printed placement or campaign. Use separate codes when placement attribution matters. Test every code on a real phone before artwork is sent to print. Keep ordinary printed codes at least 0.8 inches / 20 mm wide; use larger sizes for signs or distance scanning.', 'qrip' ); ?></p></div><?php
	}
	private static function row( $r ) { $edit = self::admin_url( array( 'action' => 'edit', 'id' => $r['id'] ) ); $status = self::action_url( 'qrip_status', array(), 'qrip_status' ); ?>
		<tr><td><strong><a href="<?php echo esc_url( $edit ); ?>"><?php echo esc_html( $r['name'] ); ?></a></strong></td><td><code><?php echo esc_html( QRip_Core::managed_url( $r['slug'] ) ); ?></code></td><td><a href="<?php echo esc_url( $r['destination'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html( $r['destination'] ); ?></a></td><td><?php echo esc_html( ucfirst( $r['status'] ) ); ?></td><td><?php echo esc_html( (string) $r['scan_count'] ); ?></td><td><?php echo esc_html( $r['last_scan_at'] ?: '—' ); ?></td><td><?php echo esc_html( $r['updated'] ); ?></td><td><a href="<?php echo esc_url( $edit ); ?>">Edit</a> · <button class="button-link qrip-copy" data-url="<?php echo esc_attr( QRip_Core::managed_url( $r['slug'] ) ); ?>">Copy URL</button> · <a href="<?php echo esc_url( self::download_url( $r['id'], 'svg' ) ); ?>">SVG</a> · <a href="<?php echo esc_url( self::download_url( $r['id'], 'png' ) ); ?>">PNG</a> <form style="display:inline" method="post" action="<?php echo esc_url( $status ); ?>"><input type="hidden" name="id" value="<?php echo esc_attr( (string) $r['id'] ); ?>"><button class="button-link"><?php echo esc_html( 'paused' === $r['status'] ? 'Activate' : 'Pause' ); ?></button></form></td></tr><?php }

	private static function form( $id ) {
		$r = $id ? QRip_Core::record( $id ) : array( 'id' => 0, 'name' => '', 'slug' => '', 'destination' => '', 'status' => 'active', 'notes' => '', 'scan_count' => 0, 'last_scan_at' => '' ); foreach ( QRip_Core::utm_keys() as $key ) { if ( ! isset( $r[ $key ] ) ) { $r[ $key ] = ''; } } if ( ! $r ) { wp_die( esc_html__( 'QR code not found.', 'qrip' ), 404 ); } $managed = $r['slug'] ? QRip_Core::managed_url( $r['slug'] ) : ''; ?>
		<div class="wrap qrip-admin"><h1><?php echo esc_html( $id ? __( 'Edit QR Code', 'qrip' ) : __( 'Add QR Code', 'qrip' ) ); ?></h1><?php if ( isset( $_GET['error'] ) ) { echo '<div class="notice notice-error"><p>' . esc_html( wp_unslash( $_GET['error'] ) ) . '</p></div>'; } ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="qrip_save"><input type="hidden" name="id" value="<?php echo esc_attr( (string) $r['id'] ); ?>"><?php wp_nonce_field( 'qrip_save' ); ?><table class="form-table"><tr><th><label for="qrip-name">Name</label></th><td><input required id="qrip-name" class="regular-text" name="name" value="<?php echo esc_attr( $r['name'] ); ?>"></td></tr><tr><th><label for="qrip-slug">Slug</label></th><td><input required pattern="[a-z0-9]+(-[a-z0-9]+)*" id="qrip-slug" class="regular-text" name="slug" value="<?php echo esc_attr( $r['slug'] ); ?>"><p class="description">URL-safe lowercase letters, numbers, and hyphens.</p></td></tr><tr><th><label for="qrip-destination">Destination URL</label></th><td><input required type="url" id="qrip-destination" class="large-text" name="destination" value="<?php echo esc_attr( $r['destination'] ); ?>"></td></tr><tr><th>Status</th><td><select name="status"><option value="active" <?php selected( $r['status'], 'active' ); ?>>Active</option><option value="paused" <?php selected( $r['status'], 'paused' ); ?>>Paused</option></select></td></tr><tr><th><label for="qrip-notes">Notes</label></th><td><textarea id="qrip-notes" class="large-text" rows="4" name="notes"><?php echo esc_textarea( $r['notes'] ); ?></textarea></td></tr></table><details><summary>UTM helper</summary><table class="form-table"><?php foreach ( QRip_Core::utm_keys() as $key ) { echo '<tr><th><label for="qrip-' . esc_attr( $key ) . '">' . esc_html( $key ) . '</label></th><td><input id="qrip-' . esc_attr( $key ) . '" class="regular-text" name="' . esc_attr( $key ) . '" value="' . esc_attr( $r[ $key ] ) . '"></td></tr>'; } ?></table></details><?php submit_button( $id ? __( 'Update QR Code', 'qrip' ) : __( 'Create QR Code', 'qrip' ) ); ?></form>
		<?php if ( $managed ) { $preview = QRip_Core::qr_result( $r['slug'], 'svg' )->getDataUri(); ?><hr><h2>Preview</h2><img width="300" height="300" alt="<?php esc_attr_e( 'QR code preview', 'qrip' ); ?>" src="<?php echo esc_attr( $preview ); ?>"><p><code><?php echo esc_html( $managed ); ?></code> <button class="button qrip-copy" data-url="<?php echo esc_attr( $managed ); ?>">Copy URL</button> <a class="button" href="<?php echo esc_url( self::download_url( $r['id'], 'svg' ) ); ?>">Download SVG</a> <a class="button" href="<?php echo esc_url( self::download_url( $r['id'], 'png' ) ); ?>">Download PNG</a></p><p><strong>Use SVG whenever possible. Do not crop the white border.</strong></p><?php } ?><p><a href="<?php echo esc_url( self::admin_url() ); ?>">← Back to QR Codes</a></p></div><script>document.addEventListener('click',function(e){if(!e.target.classList.contains('qrip-copy'))return;navigator.clipboard&&navigator.clipboard.writeText(e.target.dataset.url);e.target.textContent='Copied';});document.getElementById('qrip-name')&&document.getElementById('qrip-name').addEventListener('input',function(){var s=document.getElementById('qrip-slug');if(!s.dataset.edited){s.value=this.value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}});document.getElementById('qrip-slug')&&document.getElementById('qrip-slug').addEventListener('input',function(){this.dataset.edited='1'});</script><?php
	}
}
